# Generated by Django 4.2.15 on 2025-04-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddMissing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
                ('reporter_address', models.TextField()),
                ('missing_place_address', models.TextField()),
                ('identity_details', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='missing_person_images/')),
            ],
        ),
    ]
